### ISSUE TITLE
Anarchist does not smash

### ISSUE THREAD

**Issue by LiGoldragon** [krebs/nix-anarchy#3]
The true Anarchist has no ruler, and therefore cannot wish to smash anything. I propose:

Transcend the State

or 

Let Go of the State

**Comment by kmein** [comment]
Even though there's a sizable number of anarchists who like smashing a lot, we'll think about providing your suggestions as alternative designs. Thank you!

By the way: Have you heard of [no true Scotsman](https://en.wikipedia.org/wiki/No_true_Scotsman)?

**Comment by LiGoldragon** [comment]
@kmein Those people are ruled by anger, and therefore not anarchists. There is no fallacy there. The term Anarchist defines what can qualify as such. The Buddha would qualify. No desire, no pursuit, only trust in the Infinite Source of All.

**Comment by kmein** [comment]
I don't think that as soon as someone gets taken over by anger momentarily, they cease being an anarchist. Or which authority would decide who's an anarchist and who isn't? Believing or needing this kind of authority doesn't sound very anarchistic in my view.

I remain open to the alternative slogans you proposed and will approve PRs that implement them. However, I do not currently have the capacity to do it myself, nor do I see any problem with smashing the state.

**Comment by RTUnreal** [comment]
I am the ultimate authority on anarchism
